In [1]:
import pandas as pd 
import warnings as wr 
wr.filterwarnings("ignore")

In [2]:
df = pd.read_csv("Extensive_A_Z_medicines_dataset_of_India.csv")
df.head()

,id,name,price(₹),Is_discontinued,manufacturer_name,type,pack_size_label,short_composition1,short_composition2,substitute0,...,Consolidated_Side_Effects,use0,use1,use2,use3,use4,Chemical Class,Habit Forming,Therapeutic Class,Action Class
0,1,Augmentin 625 Duo Tablet,223.42,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,strip of 10 tablets,Amoxycillin (500mg),Clavulanic Acid (125mg),Penciclav 500 mg/125 mg Tablet,...,"Vomiting, Nausea, Diarrhea",Treatment of Bacterial infections,NaN,NaN,NaN,NaN,NaN,No,ANTI INFECTIVES,NaN
1,2,Azithral 500 Tablet,132.36,False,Alembic Pharmaceuticals Ltd,allopathy,strip of 5 tablets,Azithromycin (500mg),NaN,Zithrocare 500mg Tablet,...,"Vomiting, Nausea, Abdominal pain, Diarrhea",Treatment of Bacterial infections,NaN,NaN,NaN,NaN,Macrolides,No,ANTI INFECTIVES,Macrolides
2,3,Ascoril LS Syrup,118.00,False,Glenmark Pharmaceuticals Ltd,allopathy,bottle of 100 ml Syrup,Ambroxol (30mg/5ml),Levosalbutamol (1mg/5ml),Solvin LS Syrup,...,"Nausea, Vomiting, Diarrhea, Upset stomach, Sto...",Treatment of Cough with mucus,NaN,NaN,NaN,NaN,NaN,No,RESPIRATORY,NaN
3,4,Allegra 120mg Tablet,218.81,False,Sanofi India Ltd,allopathy,strip of 10 tablets,Fexofenadine (120mg),NaN,Lcfex Tablet,...,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,Treatment of Allergic conditions,NaN,NaN,NaN,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation)
4,4,Allegra 120mg Tablet,218.81,False,Sanofi India Ltd,allopathy,strip of 10 tablets,Fexofenadine (120mg),NaN,Lcfex Tablet,...,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,Treatment of Allergic conditions,NaN,NaN,NaN,Diphenylmethane Derivative,No,RESPIRATORY,H1 Antihistaminics (second Generation)

In [3]:
df.shape

(256476, 24)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256476 entries, 0 to 256475
Data columns (total 24 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   id                         256476 non-null  int64
 1   name                       256476 non-null  object
 2   price(₹)                   256476 non-null  float64
 3   Is_discontinued            256476 non-null  bool
 4   manufacturer_name          256476 non-null  object
 5   type                       256476 non-null  object
 6   pack_size_label            256476 non-null  object
 7   short_composition1         256476 non-null  object
 8   short_composition2         113099 non-null  object
 9   substitute0                219300 non-null  object
 10  substitute1                214803 non-null  object
 11  substitute2                211369 non-null  object
 12  substitute3                208178 non-null  object
 13  substitute4                205432 non-null  object
 14  Consolidated_Side_Effects  228385 non-null  object
 15  use0                       228385 non-null  object
 16  use1                       67854 non-null   object
 17  use2                       26126 non-null   object
 18  use3                       6832 non-null    object
 19  use4                       4626 non-null    object
 20  Chemical Class             127190 non-null  object
 21  Habit Forming              228385 non-null  object
 22  Therapeutic Class          228317 non-null  object
 23  Action Class               127425 non-null  object
dtypes: bool(1), float64(1), int64(1), object(21)
memory usage: 45.3+ MB

In [5]:
data_frame = df.drop([
    'name', 'price(₹)', 'short_composition1', 'short_composition2', 
    'substitute0', 'substitute1', 'Consolidated_Side_Effects', 
    'use0', 'Habit Forming', 'Therapeutic Class'
],axis=1)

In [6]:
data = df[['name', 'price(₹)', 'short_composition1', 'short_composition2', 
    'substitute0', 'substitute1', 'Consolidated_Side_Effects', 
    'use0', 'Habit Forming', 'Therapeutic Class']]

In [7]:
data

,name,price(₹),short_composition1,short_composition2,substitute0,substitute1,Consolidated_Side_Effects,use0,Habit Forming,Therapeutic Class
0,Augmentin 625 Duo Tablet,223.42,Amoxycillin (500mg),Clavulanic Acid (125mg),Penciclav 500 mg/125 mg Tablet,Moxikind-CV 625 Tablet,"Vomiting, Nausea, Diarrhea",Treatment of Bacterial infections,No,ANTI INFECTIVES
1,Azithral 500 Tablet,132.36,Azithromycin (500mg),NaN,Zithrocare 500mg Tablet,Azax 500 Tablet,"Vomiting, Nausea, Abdominal pain, Diarrhea",Treatment of Bacterial infections,No,ANTI INFECTIVES
2,Ascoril LS Syrup,118.00,Ambroxol (30mg/5ml),Levosalbutamol (1mg/5ml),Solvin LS Syrup,Ambrodil-LX Syrup,"Nausea, Vomiting, Diarrhea, Upset stomach, Sto...",Treatment of Cough with mucus,No,RESPIRATORY
3,Allegra 120mg Tablet,218.81,Fexofenadine (120mg),NaN,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY
4,Allegra 120mg Tablet,218.81,Fexofenadine (120mg),NaN,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY
...,...,...,...,...,...,...,...,...,...,...
256471,Ziyapod 100mg Oral Suspension,62.30,Cefpodoxime Proxetil (100mg),NaN,Qc Pod Dry Syrup,Actipod 50 Dry Syrup Orange-Lemon,"Rash, Nausea, Diarrhea",Treatment of Bacterial infections,No,ANTI INFECTIVES
256472,Zemhart 30mg Tablet,54.00,Diltiazem (30mg),NaN,Dilzex 30mg Tablet,Diltiaz 30mg Tablet,"Headache, Constipation, Dizziness, Fatigue, Fl...",Treatment of Hypertension (high blood pressure),No,CARDIAC
256473,Zivex 25mg Tablet,57.00,Hydroxyzine (25mg),NaN,HD Zine 25mg Tablet,Hydrocas 25mg Tablet,"Sedation, Nausea, Vomiting, Upset stomach, Con...",Treatment of Anxiety,No,RESPIRATORY
256474,ZI Fast 500mg Injection,152.00,Azithromycin (500mg),NaN,Zycin 500mg Injection,Aziwok 500mg Injection,"Injection site reactions (pain, swelling, redn...",Treatment of Bacterial infections,No,ANTI INFECTIVES
256475,Zyvocol 1% Dusting Powder,110.00,Clotrimazole (1% w/w),NaN,Canazole Dusting Powder,Clotrex Dusting Powder,"Blisters, Skin peeling, Swelling, Application ...",Treatment of Fungal skin infections,No,DERMA

In [8]:
data.isna().sum()

name                              0
price(₹)                          0
short_composition1                0
short_composition2           143377
substitute0                   37176
substitute1                   41673
Consolidated_Side_Effects     28091
use0                          28091
Habit Forming                 28091
Therapeutic Class             28159
dtype: int64

In [9]:
data['short_composition1'] = data['short_composition1'].fillna('')
data['short_composition2'] = data['short_composition2'].fillna('')

fill_cols = ['substitute0', 'substitute1', 'Consolidated_Side_Effects', 'use0', 'Habit Forming', 'Therapeutic Class']
for col in fill_cols:
    data[col] = data[col].fillna('Not Available')

In [10]:
data['full_composition'] = (data['short_composition1'] + " " + data['short_composition2']).str.lower().str.strip()

In [11]:
data=data.drop(["short_composition1","short_composition2"],axis=1)
data=data[data["price(₹)"]>0]

In [12]:
data

,name,price(₹),substitute0,substitute1,Consolidated_Side_Effects,use0,Habit Forming,Therapeutic Class,full_composition
0,Augmentin 625 Duo Tablet,223.42,Penciclav 500 mg/125 mg Tablet,Moxikind-CV 625 Tablet,"Vomiting, Nausea, Diarrhea",Treatment of Bacterial infections,No,ANTI INFECTIVES,amoxycillin (500mg) clavulanic acid (125mg)
1,Azithral 500 Tablet,132.36,Zithrocare 500mg Tablet,Azax 500 Tablet,"Vomiting, Nausea, Abdominal pain, Diarrhea",Treatment of Bacterial infections,No,ANTI INFECTIVES,azithromycin (500mg)
2,Ascoril LS Syrup,118.00,Solvin LS Syrup,Ambrodil-LX Syrup,"Nausea, Vomiting, Diarrhea, Upset stomach, Sto...",Treatment of Cough with mucus,No,RESPIRATORY,ambroxol (30mg/5ml) levosalbutamol (1mg/5ml)
3,Allegra 120mg Tablet,218.81,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY,fexofenadine (120mg)
4,Allegra 120mg Tablet,218.81,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY,fexofenadine (120mg)
...,...,...,...,...,...,...,...,...,...
256471,Ziyapod 100mg Oral Suspension,62.30,Qc Pod Dry Syrup,Actipod 50 Dry Syrup Orange-Lemon,"Rash, Nausea, Diarrhea",Treatment of Bacterial infections,No,ANTI INFECTIVES,cefpodoxime proxetil (100mg)
256472,Zemhart 30mg Tablet,54.00,Dilzex 30mg Tablet,Diltiaz 30mg Tablet,"Headache, Constipation, Dizziness, Fatigue, Fl...",Treatment of Hypertension (high blood pressure),No,CARDIAC,diltiazem (30mg)
256473,Zivex 25mg Tablet,57.00,HD Zine 25mg Tablet,Hydrocas 25mg Tablet,"Sedation, Nausea, Vomiting, Upset stomach, Con...",Treatment of Anxiety,No,RESPIRATORY,hydroxyzine (25mg)
256474,ZI Fast 500mg Injection,152.00,Zycin 500mg Injection,Aziwok 500mg Injection,"Injection site reactions (pain, swelling, redn...",Treatment of Bacterial infections,No,ANTI INFECTIVES,azithromycin (500mg)
256475,Zyvocol 1% Dusting Powder,110.00,Canazole Dusting Powder,Clotrex Dusting Powder,"Blisters, Skin peeling, Swelling, Application ...",Treatment of Fungal skin infections,No,DERMA,clotrimazole (1% w/w)

In [13]:
data[data["name"]=="Allegra 120mg Tablet"]

,name,price(₹),substitute0,substitute1,Consolidated_Side_Effects,use0,Habit Forming,Therapeutic Class,full_composition
3,Allegra 120mg Tablet,218.81,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY,fexofenadine (120mg)
4,Allegra 120mg Tablet,218.81,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY,fexofenadine (120mg)
734,Allegra 120mg Tablet,150.00,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY,fexofenadine (120mg)
735,Allegra 120mg Tablet,150.00,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY,fexofenadine (120mg)

In [14]:
data = (
    data
    .drop_duplicates()                             # remove exact duplicates
    .sort_values(by='price(₹)')                    # cheapest first
    .drop_duplicates(subset='name', keep='first')  # keep cheapest per medicine
    .reset_index(drop=True)
)

In [15]:
data[data["name"]=="Allegra 120mg Tablet"]

,name,price(₹),substitute0,substitute1,Consolidated_Side_Effects,use0,Habit Forming,Therapeutic Class,full_composition
193737,Allegra 120mg Tablet,150.0,Lcfex Tablet,Etofex 120mg Tablet,"Headache, Drowsiness, Dizziness, Nausea",Treatment of Sneezing and runny nose due to al...,No,RESPIRATORY,fexofenadine (120mg)

In [16]:
data

,name,price(₹),substitute0,substitute1,Consolidated_Side_Effects,use0,Habit Forming,Therapeutic Class,full_composition
0,Femidin 10mg Tablet,1.05,Facid-AC Tablet,Polyfam 10mg Tablet,"Headache, Dizziness, Diarrhea, Constipation",Treatment of Gastroesophageal reflux disease (...,No,GASTRO INTESTINAL,famotidine (10mg)
1,Setor Tablet,1.12,Alcet Tablet,Evocet Tablet,"Sleepiness, Dizziness",Treatment of Allergic conditions,No,RESPIRATORY,cetirizine (na)
2,Salmaplon 2mg Tablet,1.16,Salbid 2mg Tablet,Salbetol 2 Tablet,"Tremors, Headache, Palpitations, Increased hea...",Treatment of Chronic obstructive pulmonary dis...,No,RESPIRATORY,salbutamol (2mg)
3,Cefaxil 500mg Tablet,1.25,Cefoxim 500 Tablet,Zefu 500 Tablet,"Rash, Vomiting, Allergic reaction, Increased l...",Treatment of Bacterial infections,No,ANTI INFECTIVES,cefuroxime (500mg)
4,Povinovam Ointment,1.25,Germbeta Ointment,Afdipovidone N Ointment,"Application site reactions (burning, irritatio...",Treatment and prevention of Wound infection,No,OPHTHAL OTOLOGICALS,povidone iodine (na)
...,...,...,...,...,...,...,...,...,...
249389,Lorbriqua 100mg Tablet,312000.00,Not Available,Not Available,"Fatigue, Diarrhea, Edema (swelling), High bloo...",Treatment of Non-small cell lung cancer,No,ANTI NEOPLASTICS,lorlatinib (100mg)
249390,Imbruvica 140mg Capsule,328000.00,Bdbrut Capsule,IB-Tib Capsule,"Headache, Fever, Diarrhea, Stomatitis (Inflamm...",Mantle-cell lymphoma,No,ANTI NEOPLASTICS,ibrutinib (140mg)
249391,Besponsa 1mg Injection,330000.00,Inonza 1mg Injection,Not Available,"Low blood platelets, Decreased white blood cel...",Acute lymphoblastic leukemia,No,ANTI NEOPLASTICS,inotuzumab ozogamacin (1mg)
249392,Xtandi 40mg Soft Capsule,335635.00,Obnyx Capsule,Capmide 40mg Capsule,"Headache, Hot flashes, Weakness, High blood pr...",Prostate cancer,No,ANTI NEOPLASTICS,enzalutamide (40mg)
249393,Tecentriq 1200mg Injection,396725.00,Not Available,Not Available,"Fatigue, Weakness, Decreased appetite, Nausea,...",Treatment of Small cell lung cancer,No,ANTI NEOPLASTICS,atezolizumab (60mg/ml)

In [17]:
print(data.isna().sum())
print("Dupicated values :", data.duplicated().sum())

name                         0
price(₹)                     0
substitute0                  0
substitute1                  0
Consolidated_Side_Effects    0
use0                         0
Habit Forming                0
Therapeutic Class            0
full_composition             0
dtype: int64
Dupicated values : 0

In [18]:
data['combined_features'] = (data['full_composition'] + " " +data['use0'] + " " +data['Therapeutic Class']).str.lower()

In [19]:
data = data.drop(['full_composition','use0','Therapeutic Class'],axis=1)
data

,name,price(₹),substitute0,substitute1,Consolidated_Side_Effects,Habit Forming,combined_features
0,Femidin 10mg Tablet,1.05,Facid-AC Tablet,Polyfam 10mg Tablet,"Headache, Dizziness, Diarrhea, Constipation",No,famotidine (10mg) treatment of gastroesophagea...
1,Setor Tablet,1.12,Alcet Tablet,Evocet Tablet,"Sleepiness, Dizziness",No,cetirizine (na) treatment of allergic conditio...
2,Salmaplon 2mg Tablet,1.16,Salbid 2mg Tablet,Salbetol 2 Tablet,"Tremors, Headache, Palpitations, Increased hea...",No,salbutamol (2mg) treatment of chronic obstruct...
3,Cefaxil 500mg Tablet,1.25,Cefoxim 500 Tablet,Zefu 500 Tablet,"Rash, Vomiting, Allergic reaction, Increased l...",No,cefuroxime (500mg) treatment of bacterial infe...
4,Povinovam Ointment,1.25,Germbeta Ointment,Afdipovidone N Ointment,"Application site reactions (burning, irritatio...",No,povidone iodine (na) treatment and prevention ...
...,...,...,...,...,...,...,...
249389,Lorbriqua 100mg Tablet,312000.00,Not Available,Not Available,"Fatigue, Diarrhea, Edema (swelling), High bloo...",No,lorlatinib (100mg) treatment of non-small cell...
249390,Imbruvica 140mg Capsule,328000.00,Bdbrut Capsule,IB-Tib Capsule,"Headache, Fever, Diarrhea, Stomatitis (Inflamm...",No,ibrutinib (140mg) mantle-cell lymphoma anti n...
249391,Besponsa 1mg Injection,330000.00,Inonza 1mg Injection,Not Available,"Low blood platelets, Decreased white blood cel...",No,inotuzumab ozogamacin (1mg) acute lymphoblast...
249392,Xtandi 40mg Soft Capsule,335635.00,Obnyx Capsule,Capmide 40mg Capsule,"Headache, Hot flashes, Weakness, High blood pr...",No,enzalutamide (40mg) prostate cancer anti neop...
249393,Tecentriq 1200mg Injection,396725.00,Not Available,Not Available,"Fatigue, Weakness, Decreased appetite, Nausea,...",No,atezolizumab (60mg/ml) treatment of small cell...

In [20]:
data

,name,price(₹),substitute0,substitute1,Consolidated_Side_Effects,Habit Forming,combined_features
0,Femidin 10mg Tablet,1.05,Facid-AC Tablet,Polyfam 10mg Tablet,"Headache, Dizziness, Diarrhea, Constipation",No,famotidine (10mg) treatment of gastroesophagea...
1,Setor Tablet,1.12,Alcet Tablet,Evocet Tablet,"Sleepiness, Dizziness",No,cetirizine (na) treatment of allergic conditio...
2,Salmaplon 2mg Tablet,1.16,Salbid 2mg Tablet,Salbetol 2 Tablet,"Tremors, Headache, Palpitations, Increased hea...",No,salbutamol (2mg) treatment of chronic obstruct...
3,Cefaxil 500mg Tablet,1.25,Cefoxim 500 Tablet,Zefu 500 Tablet,"Rash, Vomiting, Allergic reaction, Increased l...",No,cefuroxime (500mg) treatment of bacterial infe...
4,Povinovam Ointment,1.25,Germbeta Ointment,Afdipovidone N Ointment,"Application site reactions (burning, irritatio...",No,povidone iodine (na) treatment and prevention ...
...,...,...,...,...,...,...,...
249389,Lorbriqua 100mg Tablet,312000.00,Not Available,Not Available,"Fatigue, Diarrhea, Edema (swelling), High bloo...",No,lorlatinib (100mg) treatment of non-small cell...
249390,Imbruvica 140mg Capsule,328000.00,Bdbrut Capsule,IB-Tib Capsule,"Headache, Fever, Diarrhea, Stomatitis (Inflamm...",No,ibrutinib (140mg) mantle-cell lymphoma anti n...
249391,Besponsa 1mg Injection,330000.00,Inonza 1mg Injection,Not Available,"Low blood platelets, Decreased white blood cel...",No,inotuzumab ozogamacin (1mg) acute lymphoblast...
249392,Xtandi 40mg Soft Capsule,335635.00,Obnyx Capsule,Capmide 40mg Capsule,"Headache, Hot flashes, Weakness, High blood pr...",No,enzalutamide (40mg) prostate cancer anti neop...
249393,Tecentriq 1200mg Injection,396725.00,Not Available,Not Available,"Fatigue, Weakness, Decreased appetite, Nausea,...",No,atezolizumab (60mg/ml) treatment of small cell...

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

tdf_vector = TfidfVectorizer() 
tdf_vector_matrix = tdf_vector.fit_transform(data["combined_features"])

In [22]:
from sklearn.metrics.pairwise import cosine_similarity


def recommend_cheapest(name, top_n=5):
    idx = data[data['name'] == name].index[0]
    
    sim_scores = cosine_similarity(tdf_vector_matrix[idx], tdf_vector_matrix).flatten()
    
    similar_indices = sim_scores.argsort()[-20:]  # take more candidates
    
    result = data.iloc[similar_indices]
    
    # return result.sort_values('price(₹)').head(top_n)
    return result["Consolidated_Side_Effects"]

In [23]:
recommend_cheapest("Allegra 120mg Tablet")

168207    Headache, Drowsiness, Dizziness, Nausea
120753    Headache, Drowsiness, Dizziness, Nausea
135388    Headache, Drowsiness, Dizziness, Nausea
147830    Headache, Drowsiness, Dizziness, Nausea
120819    Headache, Drowsiness, Dizziness, Nausea
155387    Headache, Drowsiness, Dizziness, Nausea
169093    Headache, Drowsiness, Dizziness, Nausea
137626    Headache, Drowsiness, Dizziness, Nausea
34643     Headache, Drowsiness, Dizziness, Nausea
175763    Headache, Drowsiness, Dizziness, Nausea
28235     Headache, Drowsiness, Dizziness, Nausea
148085    Headache, Drowsiness, Dizziness, Nausea
196064    Headache, Drowsiness, Dizziness, Nausea
146596    Headache, Drowsiness, Dizziness, Nausea
141802    Headache, Drowsiness, Dizziness, Nausea
160744    Headache, Drowsiness, Dizziness, Nausea
134185    Headache, Drowsiness, Dizziness, Nausea
158952    Headache, Drowsiness, Dizziness, Nausea
147744    Headache, Drowsiness, Dizziness, Nausea
145442    Headache, Drowsiness, Dizziness, Nausea
Name: Consolidated_Side_Effects, dtype: object

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

def get_recommendations_safe(medicine_name, data, tdf_vector_matrix, tfidf_vectorizer):
    # 1. User ki search ki hui medicine ka index dhoondein
    idx = data[data['name'].str.contains(medicine_name, case=False, na=False)].index
    
    if len(idx) == 0:
        return "Medicine not found."
    
    # Hum sirf pehli matching medicine uthayenge
    target_idx = idx[0]
    
    # 2. POORE matrix ki jagah sirf IS ROW ki similarity nikaalein
    # tfidf_matrix[target_idx] sirf ek row hai
    cosine_sim_row = cosine_similarity(tdf_vector_matrix[target_idx], tdf_vector_matrix).flatten()
    
    # 3. Baaki logic same rahega
    sim_scores = list(enumerate(cosine_sim_row))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Top 10 matches (excluding itself)
    recommendations = []
    current_med_price = data.iloc[target_idx]['price(₹)']
    
    for i, score in sim_scores[1:50]: # Top 50 potential matches
        if data.iloc[i]['price(₹)'] < current_med_price:
            recommendations.append(data.iloc[i])
        if len(recommendations) >= 10: # Top 5 sasti dawaiyan milte hi ruk jayein
            break
            
    return pd.DataFrame(recommendations)

In [25]:
result = get_recommendations_safe("Allegra 120mg", data, tdf_vector_matrix, tdf_vector)
print(result[['name', 'price(₹)']])

                                       name  price(₹)
40488   StayHappi Fexofenadine 120mg Tablet     36.00
52039                  Trellergy 120 Tablet     42.30
72476                  Fextric 120mg Tablet     52.00
82516                 Fexotrig 120mg Tablet     57.06
83841                 Fexopark 120mg Tablet     58.00
84040                    Fexot 120mg Tablet     58.00
84903                 Finadine 120mg Tablet     58.60
90211                  Fenedin 120mg Tablet     60.00
97058                   Fexlen 120mg Tablet     65.00
100415                 Fextral 120mg Tablet     65.40

In [26]:
def get_scanned_medicine_details(medicine_name, data):
    # Partial match se dawai dhoondein (Safe approach)
    match = data[data['name'].str.contains(medicine_name, case=False, na=False)]
    
    if match.empty:
        return "Sorry, ye dawai hamare database mein nahi hai."
    
    # Pehli matching dawai ki details nikal lein
    med_info = match.iloc[0]
    
    # Ek dictionary return karein jise frontend (Streamlit) easily padh sake
    return {
        "Name": med_info['name'],
        "Side_Effects": med_info['Consolidated_Side_Effects'],
        "Benefits":med_info['combined_features']
        # Aap chahein toh yahan 'Uses' ya 'Composition' bhi add kar sakte hain
    }

# Test karein:
details = get_scanned_medicine_details("Povinovam Ointment", data)
print(details["Name"])
print(details["Side_Effects"])
print(details["Benefits"])

Povinovam Ointment
Application site reactions (burning, irritation, itching and redness)
povidone iodine (na) treatment and prevention of wound infection ophthal otologicals